### ISSUE TITLE
There is no License specified.

### ISSUE THREAD

**Issue by jtsylve** [tmilewski/goenv#3]
Currently there is no license specified for this code. Please specify a license so that others may use the code in their projects in which ever way the author intended. 

http://choosealicense.com/no-license/

I would suggest an Apache license as it seems to be very common for Go libraries and is not very restrictive.

**Comment by jtsylve** [comment]
I'm sorry aI just noticed the license is mentioned in the readme.

**Comment by tmilewski** [comment]
:+1:
